apiVersion: v1
kind: service
metadata:
  labels:
    run: hello-docker
  name: hello-docker
  
spec:
  containers:
  - image: harik8/hello-docker
    name: hello-docker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
